<a href="https://colab.research.google.com/github/renzo-flores1/d2l_ai_exercises/blob/master/Chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Tensors

According to [PyTorch](https://pytorch.org/docs/stable/tensors.html), tensors are *multi-dimensional matrices that contain elements of a single data type*. However, in math and physics, tensors and matrices have **important differences**, and we will not be discussing this further, as this is irrelevant to the subject at hand.


## 1.1. PyTorch Implementation

To create a tensor object in PyTorch, you simply run `torch.Tensor` in Python. If we want, say a vector, like $(1\;2\;3)^T$, we just type `torch.Tensor([1,2,3])`.


In [13]:
import torch

vec1 = torch.Tensor([1,2,3])
vec1

tensor([1., 2., 3.])

We can then get the shape of a tensor by typing `t.shape`, where `t` is your tensor object. In this case, we will just type `vec1.shape`. The total number of elements can be obtained by `vec1.size()`. Since `vec1` is a vector, we expect `vec1.shape` and `vec1.size()` to be the same.

In [10]:
# Print the shape of vec1
print("vec1 shape: ", vec1.shape)

# Print size of vec1
print("vec1 size:", vec1.size())

# are vec1.size and vec1.shape the same?
print("\n\n vec1.size() == vec1.shape? ", vec1.size() == vec1.shape)

vec1 shape:  torch.Size([3])
vec1 size: torch.Size([3])


 vec1.size() == vec1.shape?  True


If you are familiar with Numpy, one can create tensor objects off of numpy arrays by feeding the numpy arrays to the `torch.Tensor` command.

In [18]:
import numpy as np

numpy_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

# turn numpy array into tensor object
arr = torch.Tensor(numpy_array)
print(arr)

# alternatively, we can just use the from_numpy command
arr1 = torch.from_numpy(numpy_array)
print(arr1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


##1.2 Tensor Operations

Tensors are very much similar to Numpy's `ndarray`, so if you can perform operation on `ndarray`s, you can do the same thing with tensor objects.

For uninitialized tensors, use `torch.empty`, for a tensor with zero as elements use `torch.zeros`, and many more. See this [page](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html) and this [page](http://d2l.ai/chapter_preliminaries/ndarray.html) for more info.

In [11]:
# create a 3x3x3 tensor with ones as entries
torch.ones(3,3,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

One can do element-wise operations too. For instance, if we have $v_1 = (1\;2\;3)^T$, and $v_2 = (4\;5\;6)^T$, then we expect $v_3 = v_1 * v_2$ to be $(4\;10\;18)^T$.

In [14]:
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([4,5,6])

v1 * v2 # should be [4 10 18]

tensor([ 4, 10, 18])

In [17]:
# We could also do matrix multiplication.
mat = torch.tensor([[-1,4,3],
                    [0,4,1],
                    [9,-9,10]])

torch.matmul(mat, v1)  # should output a vector

tensor([16, 11, 21])

**Caution:** So as not to confuse you, the columns in matrix `mat` are found in lists, $(-1\;4\;3)^T$, $(0\;4\;1)^T$ and $(9\;-9\;10)^T$. To look at more information on tensor objects, look at the references.

## 1.3 Exercises

These exercises are found in [section 2.1.8](http://d2l.ai/chapter_preliminaries/ndarray.html#exercises) of D2L. 

**Exercise 1.** Run the code in this section. Change the conditional statement `x == y` in this section to `x < y` or `x > y`, and then see what kind of tensor you can get.

In [19]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

x > y 
# this checks whether an element in x is greater than 
# the corresponding element in y
# this should give us a boolean tensor

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

# References:
1. Dive into Deep Learning, [Chapter 2](http://d2l.ai/chapter_preliminaries/index.html)

2. `torch.Tensor`, [PyTorch documentation](https://pytorch.org/docs/stable/tensors.html)